www/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

www/www/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

www/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()  # The default manager
    published = PublishedManager()  # Our custom manager
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

www/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

www/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.mail import send_mail
from django.db.models import Count
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comments': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.objects.annotate(search=SearchVector('title', 'body'), ).filter(search=query)
    return render(request, 'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'blog/post/list.html'

www/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
    {# Load the tag library #}
    {% load bootstrap4 %}
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {# Load BS Alerts #}
    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky">
    <div class="container">
        <a class="navbar-brand" href="/">Django Web App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/admin">Admin <span class="sr-only">(current)</span></a>
                </li>
            </ul><!--
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>-->
        </div>
    </div>
</nav>
<div style="height: 20px;"></div>
<div class="container">
    <div class="row">
        {% block content %}
        {% endblock %}
        <div class="col-lg-4">
            <div class="card">
                <div class="card-header">Master Blog</div>
                <div class="card-body">
                    <p>This is my blog I've written {% total_posts %} post so far.</p>
                    <h3>Latest posts</h3>
                    {% show_latest_posts 3 %}
                    <h3>Most commented posts</h3>
                    {% get_most_commented_posts as most_commented_posts %}
                    <ul>
                        {% for post in most_commented_posts %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                        {% endfor %}
                        <p><a class="btn btn-primary" href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a>
                        </p>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

www/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% load blog_tags %}

{% load crispy_forms_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

<div class="col-lg-8">
    <div class="card">
        <div class="card-header">{{ post.title }}</div>
        <div class="card-body">
            <p class="date">Published - {{ post.publish }} by {{ post.author }}</p>

            {{ post.body|markdown }}

            <p><a href="{% url 'blog:post_share' post.id %}" class="btn btn-link">Share this post</a></p>

            {% with comments.count as total_comments %}
            <h5>
                {{ total_comments }} comment{{ total_comments|pluralize }}
            </h5>
            {% endwith %}
            <hr />
            <h5>Similar post</h5>

            {% for post in similar_posts %}

            <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>

            {% empty %}
            There are no similar posts yet.
            {% endfor %}
            <hr />
            {% for comment in comments %}
            <div class="comment">
                <p class="info">Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }} </p>

                {{ comment.body|linebreaks }}
                <hr />
            </div>
            {% empty %}
            <p>There are no comments yet.</p>
            {% endfor %}
            {% if new_comment %}
            <h3>Your comment has been added.</h3>
            {% else %}
            <h3>Add a new comment</h3>
            <form action="." method="post" novalidate>
                {{ comment_form|crispy}}
                {% csrf_token %}
                <p><input type="submit" class="btn btn-primary" value="Add comment"></p>
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

www/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

www/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
<div class="col-lg-8">
    <div class="card">
        <h5 class="card-header">Blog Entries</h5>
        <div class="card-body">
            {% if tag %}
            <h4>Post tagged with "{{ tag.name }}"</h4>
            {% endif %}
            {% for post in posts %}
            <h4>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                <div class="tags">
                    Tags: {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </div>
            </h4>
            <p class="date">
                Published {{ post.publish }} by {{ post.author }}
            </p>

            {{ post.body|markdown|truncatewords_html:30 }}
            {% endfor %}
            {% include "pagination.html" with page=posts %}
        </div>
    </div>
</div>
{% endblock %}

www/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
{% if query %}
<h1>Post containing "{{ query }}"</h1>
<h3>
    {% with results.count as total_results %}
    Found {{ total_results }} result{{ total_results|pluralize }}
    {% endwith %}
</h3>
{% for post in results %}
<h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
{{ post.body|truncatewords:5 }}
{% empty %}
<p>There are no results for your query.</p>
{% endfor %}
<p><a href="{% url 'blog:post_search' %}">Search again</a></p>
{% else %}
<div class="col-lg-8">
    <div class="card">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
            <h1>Search for posts</h1>
            <form action="." method="get">
                {{ form|crispy }}
                <input type="submit" class="btn btn-primary" value="Search">
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

www/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

{% if sent %}
<div class="col-lg-8">
    <div class="card">
        <div class="card-header">Email Blog</div>
        <div class="card-body">
            <h4>E-mail successfully sent</h4>
            <p>"{{ post.title }}" was successfully sent {{ form.cleaned_data.to }}.</p>
        </div>
    </div>
</div>
{% else %}
<div class="col-lg-8">
    <div class="card">
        <div class="card-header">Share Blog Post</div>
        <div class="card-body">
            <h5>"{{ post.title }}" by e-mail</h5>
            <form method="post" action="." novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <input class="btn btn-primary" type="submit" value="Send e-mail">
            </form>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

www/blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
  {% if page.has_previous %}
  <a href="?page={{ page.previous_page_number }}">Previous</a>
  {% endif %}
  <span class="current">
  Page {{ page.number }} of {{ page.paginator.num_pages }}.
  </span>
  {% if page.has_next %}
  <a href="?page={{ page.next_page_number }}">Next</a>
  {% endif %}
  </span>
</div>